name: CMT Sanity Tests
on:
  # Remove push completely if not needed
  # push:
  #   branches: [main]

  workflow_dispatch:

  #schedule:
   # # Monday–Friday 9:00 AM IST
   # - cron: '30 3 * * 1-5' 

permissions:
  contents: write

jobs:
  test:
    runs-on: self-hosted

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # RUN D2C
    - name: Run D2C Sanity Tests
      shell: powershell
      env:
        D2C_USERNAME: ${{ secrets.D2C_USERNAME }}
        D2C_PASSWORD: ${{ secrets.D2C_PASSWORD }}
      run: |

        npx playwright test tests/D2C/ `
          -g "@D2Csanity" `
          --project=QA1_D2C `
          --workers=1

        # Rename generated HTML report
        if (Test-Path "playwright-report") {
          Rename-Item `
            playwright-report `
            d2c-report `
            -Force
        }

        # Copy JSON report
        if (Test-Path "report.json") {
          Copy-Item `
            report.json `
            d2c-report.json `
            -Force
        }

        Write-Host "D2C files:"
        Get-ChildItem

    # RUN MM
    - name: Run MM Sanity Tests
      shell: powershell
      env:
        MM_USERNAME: ${{ secrets.MM_USERNAME }}
        MM_PASSWORD: ${{ secrets.MM_PASSWORD }}
      run: |

        npx playwright test tests/MM/ `
          -g "@MMsanity" `
          --project=QA1_MM `
          --workers=1

        # Rename HTML report
        if (Test-Path "playwright-report") {
          Rename-Item `
            playwright-report `
            mm-report `
            -Force
        }

        # Copy JSON report
        if (Test-Path "report.json") {
          Copy-Item `
            report.json `
            mm-report.json `
            -Force
        }

        Write-Host "MM files:"
        Get-ChildItem

            # RUN DMTT
    - name: Run DMTT Sanity Tests
      shell: powershell
      env:
        DMTT_USERNAME: ${{ secrets.DMTT_USERNAME }}
        DMTT_PASSWORD: ${{ secrets.DMTT_PASSWORD }}
      run: |

        npx playwright test tests/DMTT/ `
          -g "@DMTTsanity" `
          --project=QA1_DMTT `
          --workers=1

        # Rename HTML report
        if (Test-Path "playwright-report") {
          Rename-Item `
            playwright-report `
            dmtt-report `
            -Force
        }

        # Copy JSON report
        if (Test-Path "report.json") {
          Copy-Item `
            report.json `
            dmtt-report.json `
            -Force
        }

        Write-Host "DMTT files:"
        Get-ChildItem

    # DEBUG
    - name: Debug generated files
      shell: powershell
      run: |

        Write-Host "Workspace Files"
        Get-ChildItem

        Write-Host "JSON Files"
        Get-ChildItem *.json

    # Upload artifacts
    - name: Upload D2C Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: d2c-report
        path: d2c-report/

    - name: Upload MM Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mm-report
        path: mm-report/

    - name: Upload DMTT Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dmtt-report
        path: dmtt-report/    



    # Deploy GitHub Pages
    - name: Deploy HTML Report
      if: always()
      shell: powershell
      run: |

        git config --global user.name "github-actions"

        git config --global user.email `
          "github-actions@github.com"

        New-Item `
          -ItemType Directory `
          -Force `
          -Path deploy\d2c

        New-Item `
          -ItemType Directory `
          -Force `
          -Path deploy\mm

        New-Item `
          -ItemType Directory `
          -Force `
          -Path deploy\dmtt

        if (Test-Path "d2c-report") {

          Copy-Item `
            "d2c-report\*" `
            "deploy\d2c\" `
            -Recurse `
            -Force
        }

        if (Test-Path "mm-report") {

          Copy-Item `
            "mm-report\*" `
            "deploy\mm\" `
            -Recurse `
            -Force
        }

        if (Test-Path "dmtt-report") {

          Copy-Item `
            "dmtt-report\*" `
            "deploy\dmtt\" `
            -Recurse `
            -Force
        }

        Set-Location deploy

        git init

        git checkout -b gh-pages

        git add .

        git commit `
          -m "Deploy reports"

        git push `
          https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git `
          gh-pages `
          --force

    # Webex notification
    - name: Send Webex Notification
      if: always()
      run: node sendWebex.js
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        
    - name: Print Time
      shell: powershell
      run: |

        Write-Host "Runner Timezone:"
        Get-TimeZone

        $utc = Get-Date

        Write-Host "UTC:"
        Write-Host (
          $utc.ToUniversalTime().ToString(
            "yyyy-MM-dd HH:mm:ss UTC"
          )
        )

        $istZone = [System.TimeZoneInfo]::FindSystemTimeZoneById(
          "India Standard Time"
        )

        $ist = [System.TimeZoneInfo]::ConvertTimeFromUtc(
          $utc.ToUniversalTime(),
          $istZone
        )

        Write-Host "IST:"
        Write-Host (
          $ist.ToString(
            "yyyy-MM-dd HH:mm:ss IST"
          )
        )

        # updated with actual report URLs after deployment 
        # Final - May 21 -version 01 
